version: "3.9"

networks:
  bot-db:
    name: bot-db
    driver: bridge
  pgadmin-db:
    name: pgadmin-db
    driver: bridge

services:
  db:
    image: postgres:14
    container_name: voice-bot-db
    restart: always
    env_file:
      - ../configs/db.env
    networks:
      - bot-db
      - pgadmin-db
    volumes:
      - ../volumes/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: voice-bot-pgadmin
    restart: always
    env_file:
      - ../configs/pgadmin.env
    networks:
      - pgadmin-db
    depends_on:
      - db
    ports:
      - 127.0.0.1:8101:80

  bot:
    image: voice-bot
    container_name: voice-bot
    build:
      context: ..
      dockerfile: dockerfiles/bot.dockerfile
      target: production
    restart: unless-stopped
    env_file: ../configs/bot.env
    tty: true
    networks:
      - bot-db
    volumes:
      - ../assets:/bot/assets
      - ../volumes/logs:/bot/logs
    command: python run.py
