version: "3.9"

networks:
  bot-db:
    name: bot-db
    driver: bridge

services:
  db:
    image: postgres:14
    container_name: voice-bot-db
    restart: always
    env_file:
      - ../configs/db.env
    networks:
      - bot-db
    volumes:
      - ../volumes/pg_data:/var/lib/postgresql/data

  bot:
    image: voice-bot
    container_name: voice-bot
    build:
      context: ..
      dockerfile: dockerfiles/bot.dockerfile
      target: production
    restart: unless-stopped
    env_file: ../configs/bot.env
    tty: true
    networks:
      - bot-db
    volumes:
      - ../assets:/bot/assets
      - ../volumes/logs:/bot/logs
    command: python run.py
